#!/bin/bash
set -xeuo pipefail

# bluespin for the Fairphone 5 (SC7280 / QCM6490 / Kodiak, aarch64).
#
# Built on plain Fedora Silverblue rather than Bluefin: Universal Blue publishes
# no aarch64 Fedora Bluefin (ublue-os/bluefin#755) and the digest pinned in
# Containerfile is a single amd64 manifest. So this shares build_rawhide.sh's
# shape, not build.sh's.
#
# This is a bluespin image that runs on FP5 hardware. The device layer under
# devices/ comes from pocketblue; none of pocketblue's opinions about what the
# image should CONTAIN come with it.
#
# ORDERING IS LOAD-BEARING -- see build_files/fp5_device.sh.

# shellcheck source=build_files/fp5_device.sh
source /ctx/build_files/fp5_device.sh
# shellcheck source=build_files/silverblue_base.sh
source /ctx/build_files/silverblue_base.sh
# shellcheck source=build_files/signing.sh
source /ctx/build_files/signing.sh
# shellcheck source=build_files/extensions.sh
source /ctx/build_files/extensions.sh

GNOME_MOBILE_REPO='copr:copr.fedorainfracloud.org:group_mobility:gnome-mobile'

############################################################################
# Device files first: pure copies, they cost a second, and they supply both
# the dracut configuration every later phase depends on and the gnome-mobile
# repo file the gate below reads. Nothing else may precede them.
############################################################################
fp5_install_device_files

############################################################################
# GATE -- before any package work.
#
# @mobility/gnome-mobile has a mobile gnome-shell for rawhide and f43, and
# NOTHING for f44: the mobile branch went 48 -> 49 -> 51, and f44 builds fail
# because mutter needs gsettings-desktop-schemas >= 51.alpha while f44 ships
# 50.1. So "gnome-mobile" and "GNOME 50" cannot both be true.
#
# Checking before the package phases means a branch without a mobile shell
# fails while the build is seconds old rather than after the full aarch64
# package work. A red f44 leg is the intended signal; the day a mobile shell
# lands there, this goes green on its own.
############################################################################
if ! dnf repoquery --repo="${GNOME_MOBILE_REPO}" --qf '%{name}\n' gnome-shell 2>/dev/null | grep -qx gnome-shell; then
    echo "::error::@mobility/gnome-mobile publishes no gnome-shell for f$(rpm -E %fedora)."
    echo "::error::The mobile shell exists for rawhide and f43 only. Nothing to build."
    exit 1
fi

############################################################################
# PHASE A -- device packages, firmware first within them.
############################################################################

# jq is needed by install_signing_policy; just is wanted anyway
dnf -y install just jq

fp5_install_device_packages

# The rescue initramfs is generated by the same %posttrans as the real one and
# doubles the boot payload. The device dracut conf already sets
# dracut_rescue_image="no"; this removes the generator too.
dnf -y remove dracut-config-rescue

# Space: this ships to a phone. English langpacks only (the full locale archive
# alone is ~230 MB), and no NVIDIA GSP blobs on a device with an Adreno GPU --
# the same two trims pocketblue applies on this base.
dnf -y swap glibc-all-langpacks glibc-langpack-en
dnf -y remove nvidia-gpu-firmware

# Every image we publish is cosign-signed, so it has to verify its own updates.
# This PATCHES whatever policy.json the base ships rather than replacing it,
# which is why nothing of pocketblue's signing config is copied in.
install_signing_policy

############################################################################
# PHASE B -- the bluespin desktop, mobile flavour.
############################################################################

# Trim before installing extension RPMs: dnf5 removes unused dependencies by
# default, and gnome-classic-session drags the GNOME Classic extension set with
# it, so removing it afterwards is a coin flip.
dnf -y remove gnome-classic-session gnome-tour

# The mobile shell is gnome-shell, mutter and gnome-settings-daemon rebuilt with
# the adaptive patch series at the same paths -- not a second shell and not a
# separate session. The COPR builds require each other at =version, so move all
# three in ONE transaction: distro-sync rather than remove-then-install because
# `dnf remove gnome-shell` on Silverblue takes gdm, gnome-session and every
# gnome-shell-extension-* with it, and a single transaction cannot leave a
# half-desktop behind if it fails.
#
# Do this BEFORE the extension RPMs below, so anything the sync does disturb is
# reinstated by them.
dnf -y distro-sync --repo="${GNOME_MOBILE_REPO}" --allowerasing \
    gnome-shell mutter gnome-settings-daemon

# Prove we got the mobile build and not Fedora's. Without this a repo that went
# missing would silently ship stock GNOME under a mobile image name -- which is
# exactly what pocketblue's f44 images do.
dnf repoquery --installed --qf '%{from_repo}\n' gnome-shell | grep -q gnome-mobile

# Leave no COPR live in the shipped image: an enabled repo lets a later
# `rpm-ostree install` resolve gnome-shell back to Fedora's build.
dnf config-manager setopt "${GNOME_MOBILE_REPO}.enabled=0"

# Bluefin's base normally supplies these. Same set build_rawhide.sh asks for on
# a plain base -- Firefox included: what the image contains is bluespin's call,
# not the device's.
dnf -y install \
    gnome-tweaks \
    firefox \
    mozilla-openh264 \
    gnome-shell-extension-just-perfection \
    gnome-shell-extension-screen-autorotate

install_ublue_tools

# Mobile hardware this device actually has: telephony, SMS, and the haptics
# driving its AW86927 vibrator.
dnf -y install \
    calls \
    chatty \
    feedbackd \
    tecla

# Our own COPR extensions, same as the shipping variants
dnf -y copr enable lorbus/network-displays
dnf -y install gnome-network-displays gnome-network-displays-extension
dnf -y copr disable lorbus/network-displays

install_vendored_extensions
# Nothing on this base supplies Bluefin's vendored set, so bring our forks
install_bluefin_replacement_extensions
# mosaicwm is not installed here: it is a tiling window manager, and this shell
# runs everything fullscreen on a 6.4" panel.
assert_extensions_declare_shell \
    weatherornot@somepaulo.github.io \
    nekotorch@nekocwd.gitlab.com

# Mobile defaults. The screen-keyboard key is the important one: without it
# there is no on-screen keyboard and the device has no text input at all.
# Installed before write_enabled_extensions_override so it picks up that
# function's glib-compile-schemas rather than needing a second one.
install -Dm0644 /ctx/files/usr/share/glib-2.0/schemas/zz3-bluespin-fp5.gschema.override \
    /usr/share/glib-2.0/schemas/zz3-bluespin-fp5.gschema.override

# The disk image's blueprint creates the `bluespin` rescue account, but
# image-builder does not materialise blueprint users' home directories
# (osbuild/image-builder#2596) and /var/home here is a fresh btrfs subvolume,
# so nothing else does either. Seed it at boot -- without this, the account
# documented as the only way in lands in a nonexistent home directory.
install -Dm0644 /ctx/files/usr/lib/tmpfiles.d/bluespin-fp5-homedir.conf \
    /usr/lib/tmpfiles.d/bluespin-fp5-homedir.conf

# Enabled by default. Deltas from the desktop variants, all deliberate:
#   + nekotorch    -- this device has a torch LED, which is what nekotorch's
#                     99-flash.rules udev rule exists for. Off everywhere else
#                     because desktops have no torch.
#   + screen-rotate-- explicit orientation lock.
#   - search-light -- a centred overlay bound to a keyboard shortcut, on a
#                     device with no keyboard.
#   - weatherornot -- renders next to the clock; a portrait status bar has no
#                     room. Installed, one word from being on.
ENABLED_EXTENSIONS=(
    appindicatorsupport@rgcjonas.gmail.com
    bazaar-integration@kolunmi.github.io
    caffeine@patapon.info
    gradia-integration@alexandervanhee.github.io
    nekotorch@nekocwd.gitlab.com
    network-displays@gnome.org
    screen-rotate@shyzus.github.io
)
write_enabled_extensions_override "${ENABLED_EXTENSIONS[@]}"

# Flatpaks, the same sets the desktop variants ship. Entries with no aarch64
# build on Flathub (six today) simply never install on the device;
# validate-flatpaks.yml emits a ::warning:: for each of them against the files'
# `# bluespin-arches:` headers, so the gap is visible in CI rather than
# discovered on the phone.
install_flathub_and_preinstall \
    /ctx/files/usr/share/flatpak/preinstall.d/bluespin.preinstall \
    /ctx/files/usr/share/flatpak/preinstall.d/bluespin-extra.preinstall

############################################################################
# PHASE C -- kernel. Nothing may follow this except cleanup.
############################################################################
fp5_swap_kernel

############################################################################
# Cleanup -- shared with the rawhide image, see silverblue_base.sh.
############################################################################
cleanup_silverblue_image
