#!/bin/bash
# The desktop defaults bluespin sets, as one table.
#
# Every setting here was reviewed against Fedora's own default and taken
# deliberately; what is NOT here is as deliberate as what is, and Fedora's
# default stands for everything unlisted -- accent colour, hot corners,
# wallpaper, search providers, most of Ptyxis. See docs/desktop-defaults.md
# for the reasoning per setting.
#
# zz2 sorts after anything a base might ship, so these win.
set -xeuo pipefail

DESKTOP_OVERRIDE=/usr/share/glib-2.0/schemas/zz2-bluespin-desktop.gschema.override
KEYBINDINGS_DCONF=/etc/dconf/db/distro.d/50-bluespin-keybindings
# Fixed, not generated: Ptyxis keys its profiles by uuid, and a uuid that
# changed per build would orphan the profile the palette is attached to.
PTYXIS_PROFILE_UUID=fa994a990ef541da995116df0e724467

# Some of these are wrong on a phone, so the mobile platform keeps Fedora's
# default for them: a portrait status bar has no room for the weekday, there
# is no numpad to switch on, the power button should suspend rather than open
# a dialog, and minimise/maximise mean nothing where every window is
# fullscreen.
write_desktop_defaults() {
    local platform=$1 mobile=0
    [[ "${platform}" == "bluespin-fp5" ]] && mobile=1

    {
        echo "# Generated by build_files/desktop.sh -- edit the table there."
        echo

        echo "[org.gnome.desktop.interface]"
        # Fedora ships Adwaita Mono; JetBrains Mono is a deliberate choice, and
        # the package is installed alongside it rather than replacing it.
        echo "monospace-font-name='JetBrains Mono 11'"
        # Subpixel rather than greyscale antialiasing
        echo "font-antialiasing='rgba'"
        [[ "${mobile}" -eq 0 ]] && echo "clock-show-weekday=true"
        echo

        echo "[org.gnome.desktop.wm.preferences]"
        echo "titlebar-font='Adwaita Sans Bold 12 @wght=700'"
        # Fedora shows only a close button
        [[ "${mobile}" -eq 0 ]] && echo "button-layout=':minimize,maximize,close'"
        echo

        if [[ "${mobile}" -eq 0 ]]; then
            echo "[org.gnome.desktop.peripherals.keyboard]"
            echo "numlock-state=true"
            echo
            echo "[org.gnome.settings-daemon.plugins.power]"
            echo "power-button-action='interactive'"
            echo
        fi

        echo "[org.gnome.mutter]"
        # 5s is aggressive enough that a busy application gets reported as
        # unresponsive while it is merely busy
        echo "check-alive-timeout=uint32 20000"
        echo

        echo "[org.gtk.Settings.FileChooser]"
        # GTK4's default is already this; only GTK3 needs saying
        echo "sort-directories-first=true"
        echo

        # The dash, in order. Neither stock list survives contact with this
        # image: Bluefin's names Readymade (Fyra Labs' ISO installer, not on
        # Flathub at all), Code (dx only) and org.mozilla.Thunderbird (Flathub
        # carries two Mozilla-published Thunderbirds; the preinstalled one
        # here is the lowercase id), and both lists name org.gnome.Software,
        # which this image removes. GNOME drops favourites whose desktop file
        # is missing without saying so, which left a dash of three icons.
        echo "[org.gnome.shell]"
        local favourites=(
            org.mozilla.firefox.desktop      # RPM
            org.mozilla.thunderbird.desktop  # flatpak, note the lowercase id
            org.gnome.Nautilus.desktop       # RPM
            io.github.kolunmi.Bazaar.desktop # flatpak
            org.gnome.Calendar.desktop       # flatpak
            org.gnome.Calculator.desktop     # flatpak
            org.gnome.TextEditor.desktop     # flatpak
        )
        # VS Code is installed by the developer layer only
        [[ "${platform}" == "bluespin-dx" ]] && favourites+=(code.desktop)
        printf "favorite-apps = ["
        printf "'%s', " "${favourites[@]}" | sed 's/, $//'
        printf "]\n"
        echo

        # App-grid folders. GNOME upstream ships none at all -- a flat grid --
        # and Bluefin's nine include two (YaST, Pardus) that nothing ever
        # defines and two (Wine, GamingUtilities) that list apps this image
        # does not ship. These are category-driven instead, so they fill
        # themselves from whatever is installed, including what a user adds
        # later; GNOME hides a folder with no matching apps, so defining one
        # that is empty today costs nothing and files tomorrow's app for free.
        echo "[org.gnome.Ptyxis]"
        # A terminal that reopens yesterday's tabs, at yesterday's size, is a
        # surprise rather than a convenience
        echo "restore-session=false"
        echo "restore-window-size=false"
        # The profile the palette below belongs to. Ptyxis keys profiles by
        # uuid; this one is ours and stays fixed so the setting survives
        # rebuilds.
        echo "profile-uuids=['${PTYXIS_PROFILE_UUID}']"
        echo "default-profile-uuid='${PTYXIS_PROFILE_UUID}'"
        echo

        echo "[org.gnome.desktop.app-folders]"
        echo "folder-children = ['Utilities', 'Graphics', 'Office', 'Internet', 'Multimedia', 'System', 'Games', 'Development']"
        echo

        echo "[org.gnome.desktop.wm.keybindings]"
        echo "show-desktop=['<Super>d']"
        # Fedora puts app-switching on both Super+Tab and Alt+Tab, and leaves
        # window-switching unbound. Split them: Super+Tab cycles applications,
        # Alt+Tab cycles windows.
        echo "switch-applications=['<Super>Tab']"
        echo "switch-applications-backward=['<Shift><Super>Tab']"
        echo "switch-windows=['<Alt>Tab']"
        echo "switch-windows-backward=['<Shift><Alt>Tab']"
        # Move input-source switching off Super+Space
        echo "switch-input-source=['<Shift><Super>space']"
        echo "switch-input-source-backward=['']"
        # Fedora also binds Alt+F5, which collides with application shortcuts
        echo "unmaximize=['<Super>Down']"
        echo

        echo "[org.gnome.settings-daemon.plugins.media-keys]"
        echo "home=['<Super>e']"
        # The bindings themselves are relocatable schemas, so they live in
        # dconf below; this only says which of them are active.
        echo "custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/']"
    } > "${DESKTOP_OVERRIDE}"

    # Ctrl+Alt+T is the shortcut every other desktop has and GNOME does not.
    # Bound straight to Ptyxis, which every bluespin image ships. Bluefin uses
    # xdg-terminal-exec here, which resolves whichever terminal the user
    # prefers -- a 97 KB package that nothing else in the image needs, for a
    # choice this image does not otherwise offer.
    install -d "$(dirname "${KEYBINDINGS_DCONF}")"
    cat > "${KEYBINDINGS_DCONF}" << 'EOF'
# Generated by build_files/desktop.sh. Custom keybindings are relocatable
# schemas, which a gschema override cannot set, so they live here; the list of
# active ones is in zz2-bluespin-desktop.gschema.override.

[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0]
binding='<Control><Alt>t'
command='ptyxis --new-window'
name='Terminal'

[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1]
binding='<Control><Alt>Return'
command='ptyxis --new-window'
name='Terminal (alternative)'

# The shortcut Windows and KDE users reach for, pointed at the system monitor
# this image actually ships. Bluefin runs its own missioncenter-helper here,
# an unowned script that exists only on that base; the flatpak is preinstalled
# on every platform, so calling it directly behaves the same everywhere.
[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2]
binding='<Control><Shift>Escape'
command='flatpak run io.missioncenter.MissionCenter'
name='System Monitor'

# Smile, the emoji picker (preinstalled flatpak). Two bindings, as Bluefin
# has: Super+period is what Windows users reach for, Ctrl+Alt+space is the
# one that works when Super is spoken for. Neither collides with GNOME's own
# in-text-field emoji chooser on Ctrl+period.
[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3]
binding='<Super>period'
command='flatpak run it.mijorus.smile'
name='Emoji picker'

[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4]
binding='<Control><Alt>space'
command='flatpak run it.mijorus.smile'
name='Emoji picker (alternative)'

# The folders themselves are relocatable schemas, which a gschema override
# cannot set, so their definitions live here too. Names come from GNOME's own
# .directory files, which carry translations for 84-118 languages, rather than
# hardcoded English.

[org/gnome/desktop/app-folders/folders/Utilities]
name='X-GNOME-Utilities.directory'
translate=true
categories=['X-GNOME-Utilities']
apps=['com.github.tchx84.Flatseal.desktop', 'io.github.flattool.Warehouse.desktop', 'com.mattjakeman.ExtensionManager.desktop', 'io.github.flattool.Ignition.desktop', 'page.tesk.Refine.desktop', 'it.mijorus.smile.desktop']

[org/gnome/desktop/app-folders/folders/Graphics]
name='Graphics.directory'
translate=true
categories=['Graphics']

[org/gnome/desktop/app-folders/folders/Office]
name='Office.directory'
translate=true
categories=['Office']

[org/gnome/desktop/app-folders/folders/Internet]
name='Network.directory'
translate=true
categories=['Network']

[org/gnome/desktop/app-folders/folders/Multimedia]
name='AudioVideo.directory'
translate=true
categories=['AudioVideo']

[org/gnome/desktop/app-folders/folders/System]
name='System-Tools.directory'
translate=true
categories=['System']

[org/gnome/desktop/app-folders/folders/Games]
name='Game.directory'
translate=true
categories=['Game']

# Defined on every platform, not just the developer one: it is empty and
# therefore invisible until something matches, and then a development app the
# user installs themselves lands in it without anyone editing this file. The
# two named apps come with bluespin-dx; naming an app that is not installed is
# simply ignored.
[org/gnome/desktop/app-folders/folders/Development]
name='Development.directory'
translate=true
categories=['Development', 'IDE']
apps=['code.desktop', 'virt-manager.desktop']

# Catppuccin, from the four variants Ptyxis already bundles. Bluefin instead
# ships a "catppuccin-dynamic" file pairing Latte (light) with Mocha (dark),
# but the terminal here is always dark (see the interface-style decision), so
# its light half could never appear -- and the dark half is byte-identical to
# this built-in. Skipping the file also skips its limitation: Ptyxis reads
# palettes from the user's data directory only, so a shipped file has to go
# through /etc/skel and reaches accounts created after installation, while a
# bundled palette works for everyone immediately.
[org/gnome/Ptyxis/Profiles/PTYXIS_UUID_PLACEHOLDER]
palette='Catppuccin Mocha'

# Search Light's own settings live in dconf, since its schema is not in the
# global schema directory. Only the shortcut is set: Super+Space is free
# because input-source switching moved to Shift+Super+Space above, and
# without this it would do nothing (upstream ships no default shortcut). Its
# appearance stays upstream's -- Bluefin's size, border and colour tweaks are
# deliberately not carried over.
[org/gnome/shell/extensions/search-light]
shortcut-search=['<Super>space']
EOF

    # The keybindings heredoc above is quoted so nothing in it expands; put
    # the profile uuid in afterwards.
    sed -i "s/PTYXIS_UUID_PLACEHOLDER/${PTYXIS_PROFILE_UUID}/" "${KEYBINDINGS_DCONF}"

    dconf update
    glib-compile-schemas /usr/share/glib-2.0/schemas
}
