#!/bin/bash
set -xeuo pipefail

# The Fairphone 5 layer (SC7280 / QCM6490 / Kodiak, aarch64): what makes the
# bluespin image run on FP5 hardware, layered on the same bluespin image as
# dx and surface -- the phone shares the whole desktop payload and diverges
# only where a phone must. The device layer under devices/ comes from
# pocketblue; none of pocketblue's opinions about what the image should
# CONTAIN come with it.
#
# ORDERING IS LOAD-BEARING -- see build_files/fp5_device.sh. The initramfs
# is generated by the kernel RPM's %posttrans, so it only picks up the
# dracut configuration and the firmware if both are already on disk: device
# files first, kernel last. Only variant-finish.sh (file-only work) may run
# after this script.

# shellcheck source=build_files/fp5_device.sh
source /ctx/build_files/fp5_device.sh

GNOME_MOBILE_REPO='copr:copr.fedorainfracloud.org:group_mobility:gnome-mobile'

############################################################################
# Device files first: pure copies, they cost a second, and they supply both
# the dracut configuration every later phase depends on and the gnome-mobile
# repo file the gate below reads. Nothing else may precede them.
############################################################################
fp5_install_device_files

############################################################################
# GATE -- before any package work.
#
# Only a branch where @mobility/gnome-mobile publishes a mobile gnome-shell
# can produce a working image (f45 and rawhide today). Checking before the
# package phases means a branch without one fails while the build is
# seconds old rather than after the full aarch64 package work.
############################################################################
if ! dnf repoquery --repo="${GNOME_MOBILE_REPO}" --qf '%{name}\n' gnome-shell 2>/dev/null | grep -qx gnome-shell; then
    echo "::error::@mobility/gnome-mobile publishes no gnome-shell for f$(rpm -E %fedora). Nothing to build."
    exit 1
fi

############################################################################
# Device packages, firmware first within them.
############################################################################
fp5_install_device_packages

# The rescue initramfs is generated by the same %posttrans as the real one
# and doubles the boot payload. The device dracut conf already sets
# dracut_rescue_image="no"; this removes the generator too.
dnf -y remove dracut-config-rescue

# Space: this ships to a phone. English langpacks only (the full locale
# archive alone is ~230 MB), and no NVIDIA GSP blobs on a device with an
# Adreno GPU -- the same two trims pocketblue applies on this base.
dnf -y swap glibc-all-langpacks glibc-langpack-en
dnf -y remove nvidia-gpu-firmware

# Sessions that mean nothing on a 6.4" panel. GNOME Classic in particular
# drags its extension set along, so it goes before anything touches the
# shell below.
dnf -y remove gnome-classic-session gnome-tour

############################################################################
# The mobile shell: gnome-shell, mutter and gnome-settings-daemon rebuilt
# with the adaptive patch series at the same paths -- not a second shell and
# not a separate session. The COPR builds require each other at =version, so
# move all three in ONE transaction: distro-sync rather than
# remove-then-install because `dnf remove gnome-shell` on Silverblue takes
# gdm, gnome-session and every gnome-shell-extension-* with it, and a single
# transaction cannot leave a half-desktop behind if it fails.
#
# --enablerepo, NOT --repo: the mobile shell may need newer libraries than
# the COPR itself carries, and --repo= hides every other repo from the
# resolver, turning that dependency into "nothing provides" and silently
# skipping gnome-shell as broken. With the Fedora repos visible the
# dependency resolves, and the three named packages still land on the mobile
# builds because those out-version Fedora's.
#
# allow_vendor_change: replacing Fedora's shell with the COPR build IS a
# vendor change, which newer dnf5 blocks by default -- the same silent
# "Nothing to do" the surface libwacom swap hit. The from_repo assert
# below would catch it, but red-for-a-known-reason is just a worse
# spelling of this setopt.
############################################################################
dnf -y distro-sync --enablerepo="${GNOME_MOBILE_REPO}" --allowerasing \
    --setopt=allow_vendor_change=true \
    gnome-shell mutter gnome-settings-daemon

# Prove we got the mobile build and not Fedora's. Without this a repo that
# went missing would silently ship stock GNOME under a mobile image name.
dnf repoquery --installed --qf '%{from_repo}\n' gnome-shell | grep -q gnome-mobile

# Leave no COPR live in the shipped image: an enabled repo lets a later
# `rpm-ostree install` resolve gnome-shell back to Fedora's build.
dnf config-manager setopt "${GNOME_MOBILE_REPO}.enabled=0"

# Telephony and mobile hardware userland: calls, the SMS/MMS stack, the
# chat app that fronts it, haptics for the AW86927 vibrator, and the OSK
# layout viewer. dx carries the same calls/SMS set for telephony
# development; here it is the phone's actual phone function.
dnf -y install \
    calls \
    chatty \
    feedbackd \
    mmsd-tng \
    purple-mm-sms \
    tecla

# Mobile defaults the desktop table cannot express -- the screen-keyboard
# key above all: without it there is no on-screen keyboard and a device
# with no physical keyboard has no text input at all, including at the
# password prompt. Installed here; variant-finish.sh's glib-compile-schemas
# run picks it up.
install -Dm0644 /ctx/files/usr/share/glib-2.0/schemas/zz3-bluespin-fp5.gschema.override \
    /usr/share/glib-2.0/schemas/zz3-bluespin-fp5.gschema.override

# The disk image's blueprint creates the `bluespin` rescue account, but
# image-builder does not materialise blueprint users' home directories
# (osbuild/image-builder#2596) and /var/home here is a fresh btrfs
# subvolume, so nothing else does either. Seed it at boot -- without this,
# the account documented as the only way in lands in a nonexistent home
# directory.
install -Dm0644 /ctx/files/usr/lib/tmpfiles.d/bluespin-fp5-homedir.conf \
    /usr/lib/tmpfiles.d/bluespin-fp5-homedir.conf

############################################################################
# Kernel LAST -- see the ordering note at the top. fp5_swap_kernel asserts
# the initramfs contains the Qualcomm drivers and firmware.
############################################################################
fp5_swap_kernel

# The bluespin layer built v4l2loopback for the stock kernel this variant
# just removed; the module went with the kernel's module directory, so drop
# the configs that would try to load it on every boot. The sc7280 kernel
# carries no v4l2loopback (nothing builds it for that kernel yet).
rm -f /usr/lib/modules-load.d/v4l2loopback.conf \
    /usr/lib/modprobe.d/98-v4l2loopback.conf
