#!/bin/bash
# Fairphone 5 (SC7280 / QCM6490 / Kodiak) hardware enablement, derived from
# pocketblue's devices/fairphone-fp5/build at commit 7481fac.
#
# Split into three phases ON PURPOSE, because the ordering is load-bearing and
# its failure mode is a phone that does not boot. The initramfs is generated by
# the kernel RPM's %posttrans, so it only picks up the dracut configuration and
# the firmware if both are already on disk. Phase 1 must therefore run before
# anything else, and phase 3 must run after everything else.
set -xeuo pipefail

DEV=/ctx/devices/fairphone-fp5

# --- Phase 1: files only. MUST run first. -----------------------------------
fp5_install_device_files() {
    # cp -arfT, not install -D: preserves the local-fs.target.wants symlink,
    # the 0755 helper modes and the directory structure verbatim, which keeps
    # these trees byte-diffable against pocketblue.
    cp -arfT /ctx/devices/common/files/etc /etc
    cp -arfT /ctx/devices/common/files/usr /usr
    cp -arfT "${DEV}/files/etc" /etc
    cp -arfT "${DEV}/files/usr" /usr

    # set-bt-mac is tracked mode 0644 upstream; the others are already 0755.
    chmod +x /usr/libexec/fp5-load-dsp /usr/libexec/set-bt-mac \
        /usr/libexec/set-modem-sim-slot /usr/libexec/ucsi-rebind \
        /usr/libexec/grow-rootfs

    # Assert the linchpin landed. Without this file the kernel's %posttrans in
    # phase 3 builds an initramfs with no Qualcomm drivers and the device does
    # not get past u-boot.
    [[ -f /usr/lib/dracut/dracut.conf.d/50-fairphone-fp5.conf ]]
}

# --- Phase 2: packages. Firmware FIRST, within this phase. ------------------
fp5_install_device_packages() {
    # Firmware before anything else: the dracut conf from phase 1 names these
    # by path in install_items, which fails hard on a missing file (unlike
    # install_optional_items, which tolerates it).
    dnf -y install atheros-firmware qcom-firmware

    dnf -y install \
        qrtr \
        rmtfs \
        tqftpserv \
        alsa-ucm-utils \
        bluez \
        libcamera \
        libcamera-ipa \
        hexagonrpc \
        libssc

    # alsa-ucm-conf-qcom-sc7280 used to ship a copy of the whole ucm2 tree,
    # which conflicts with alsa-ucm on every file the two have in common. Newer
    # builds carry only the device configuration and require alsa-ucm instead.
    # Handle both, keyed on whether the available package depends on alsa-ucm.
    local alsa_repo='copr:copr.fedorainfracloud.org:pocketblue:sc7280'
    if dnf repoquery --repo="${alsa_repo}" --requires alsa-ucm-conf-qcom-sc7280 | grep -qx 'alsa-ucm'; then
        dnf -y install --enable-repo="${alsa_repo}" alsa-ucm-conf-qcom-sc7280
    else
        # old build: alsa-ucm has to go first, and alsa-utils depends on it
        dnf -y swap --enable-repo="${alsa_repo}" --allowerasing \
            alsa-ucm alsa-ucm-conf-qcom-sc7280
    fi

    # Fedora's iio-sensor-proxy has no Qualcomm Sensor Core support and finds
    # no sensors on this hardware. Fedora's release is higher, so this has to be
    # a swap rather than an upgrade.
    dnf -y swap --repo='copr:copr.fedorainfracloud.org:pocketblue:common' \
        iio-sensor-proxy iio-sensor-proxy
    ldd /usr/libexec/iio-sensor-proxy | grep -q libssc

    # --enable-repo rather than --repo: blob-wrangler needs kmod, and --repo
    # would restrict resolution to the copr alone.
    dnf -y install --enable-repo='copr:copr.fedorainfracloud.org:group_mobility:common' \
        blob-wrangler
    dnf -y install make-dynpart-mappings

    # The rpm's own fairphone,fp5.toml carries the full extraction set: the
    # folders section (ADSP acdb/sensors/dsp trees plus the registry from
    # persist) and the sns_reg_config -> sns_reg.conf per-file copy
    # (samcday/blob-wrangler#14). This image ships no override, so fail the
    # build loudly if an older rpm without them gets installed - without the
    # registry content the ADSP crash-loops the device, and without
    # sns_reg.conf its sensor task aborts.
    grep -q '^folders' "/usr/share/blob-wrangler/configs/fairphone,fp5.toml"
    grep -q 'sns_reg.conf' "/usr/share/blob-wrangler/configs/fairphone,fp5.toml"

    # /usr is read-only at runtime, so point the two paths that receive
    # extracted content at /var. /usr/lib/firmware/updates is searched by the
    # kernel ahead of /usr/lib/firmware, and hexagonrpcd looks under
    # /usr/share/qcom.
    rm -rf /usr/lib/firmware/updates
    ln -sf /var/lib/firmware-extract /usr/lib/firmware/updates
    mkdir -p /usr/share/qcom/qcm6490/Fairphone
    ln -sf /var/lib/blob-wrangler/sensors /usr/share/qcom/qcm6490/Fairphone/fp5

    # SELinux policy modules (CIL). Note the /var prune at the end of the build
    # deletes /var/lib/selinux, so `semodule -l` is empty on the running device
    # -- that is fine and matches pocketblue, because the compiled binary policy
    # the kernel loads lives under /etc/selinux/targeted/policy/.
    semodule -X 400 -i \
        /usr/share/selinux/packages/iio-sensor-proxy-qrtr.cil \
        /usr/share/selinux/packages/systemd-system-control.cil

    # Recovery path. A phone that fails to reach the panel is undiagnosable
    # without these, and unlike a laptop there is no console to fall back to.
    dnf -y install usb-network
    systemctl enable usb-network.service
    systemctl enable sshd.service
    systemctl enable serial-getty@ttyGS0.service

    systemctl enable blob-wrangler.service
    systemctl enable \
        hexagonrpcd-adsp-sensorspd.service \
        hexagonrpcd-adsp-rootpd.service \
        rmtfs.service \
        tqftpserv.service

    # FP5 boots Android-style A/B via u-boot, not EFI/bootupd
    systemctl mask bootloader-update.service
}

# --- Phase 3: kernel. MUST run last. ----------------------------------------
fp5_swap_kernel() {
    dnf -y remove \
        kernel \
        kernel-core \
        kernel-modules \
        kernel-modules-core \
        kernel-modules-extra

    dnf -y install --repo='copr:copr.fedorainfracloud.org:group_mobility:sc7280' \
        kernel \
        kernel-core \
        kernel-modules \
        kernel-modules-core \
        kernel-modules-extra

    # The whole point of the phase ordering. These turn a silent regression into
    # a build failure: if anything ever moves the dracut conf or the firmware to
    # after the kernel, the initramfs comes out without the Qualcomm drivers and
    # we find out here rather than on a device that will not boot.
    local kver listing
    kver="$(rpm -q --qf '%{VERSION}-%{RELEASE}.%{ARCH}\n' kernel-core)"
    [[ -f "/usr/lib/modules/${kver}/initramfs.img" ]]
    # List once and grep the file. Piping into grep -q would SIGPIPE lsinitrd
    # when the match lands before the end of its output (grep exits, lsinitrd's
    # next write gets EPIPE, the pipeline returns 141) and under pipefail that
    # fails every SUCCESSFUL build.
    listing="$(mktemp)"
    lsinitrd "/usr/lib/modules/${kver}/initramfs.img" > "${listing}"
    grep -q 'qca/msbtfw11.mbn' "${listing}"
    grep -qE '(^|/)ufs_qcom\.ko' "${listing}"
    rm -f "${listing}"
}
