# full-desktop.Brewfile
# Opt-in catalog of GNOME Circle and community flatpak applications beyond
# bluespin's preinstalled set. Install with:
#   ujust bbrew
# and select "full-desktop" from the menu.

# Not preinstalled on any variant
flatpak "app.drey.Biblioteca"
flatpak "app.drey.Elastic"
flatpak "com.github.finefindus.eyedropper"
flatpak "com.github.flxzt.rnote"
flatpak "com.github.huluti.Curtail"
flatpak "com.github.johnfactotum.Foliate"
flatpak "com.github.maoschanz.drawing"
flatpak "com.github.neithern.g4music"
flatpak "com.github.rajsolai.textsnatcher"
flatpak "com.rafaelmardojai.Blanket"
flatpak "com.ranfdev.Notify"
flatpak "de.haeckerfelix.AudioSharing"
flatpak "de.haeckerfelix.Fragments"
flatpak "dev.bragefuglseth.Fretboard"
flatpak "dev.Cogitri.Health"
flatpak "dev.geopjr.Calligraphy"
flatpak "dev.geopjr.Collision"
flatpak "dev.geopjr.Tuba"
flatpak "eu.fortysixandtwo.chessclock"
flatpak "im.dino.Dino"
flatpak "info.febvre.Komikku"
flatpak "io.github.diegoivan.pdf_metadata_editor"
flatpak "io.github.lainsce.Khronos"
flatpak "io.github.mrvladus.List"
flatpak "io.github.seadve.Mousai"
flatpak "io.gitlab.adhami3310.Converter"
flatpak "it.mijorus.smile"
flatpak "org.freedesktop.Piper"
flatpak "org.gaphor.Gaphor"
flatpak "org.gnome.Builder"
flatpak "org.gnome.design.Emblem"
flatpak "org.gnome.design.IconLibrary"
flatpak "org.gnome.gitlab.cheywood.Buffer"
flatpak "org.gnome.gitlab.cheywood.Pulp"
flatpak "org.gnome.gitlab.YaLTeR.Identity"
flatpak "org.gnome.Solanum"
flatpak "org.gnome.World.Citations"
flatpak "org.nickvision.cavalier"
flatpak "org.nickvision.tubeconverter"
flatpak "page.kramo.Cartridges"
flatpak "re.sonny.Commit"
flatpak "re.sonny.Tangram"
#flatpak "org.gnome.World.PikaBackup"
